### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by larshp** [AkyshBaymuhammedov/ADT_TODO_Plugin_ABAP#1]
hi, 
can you help adding a license file?

https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by AkyshBaymuhammedov** [comment]
Hi Lars! I added a license now. Sorry for the late reply, I check the repository rarely and didn't see your message...
If you need help please contact me via email akysh.1196@gmail.com so that I can respond as fast as possible.

**Comment by larshp** [comment]
no problem, thanks
