### ISSUE TITLE
Cannot install on NW 752 SP04 dev edition

### ISSUE THREAD

**Issue by christianguenter2** [AkyshBaymuhammedov/ADT_TODO_Plugin_ABAP#2]
STRING_T is not know as it is part of ERP software component.

![image](https://user-images.githubusercontent.com/17437789/88383035-fdd54100-cda9-11ea-842b-dd580297371e.png)

**Comment by AkyshBaymuhammedov** [comment]
Hi Christian! Sorry for the late reply. I replaced STRING_T with a local table type so it should work now.
